### PR TITLE
Add RaftKVDatabase from https://github.com/archiecobbs/jsimpledb

### PR DESCRIPTION
**Pull request by archiecobbs**

### CODE REVIEW

**Comment by ongardie** [comment]
Thanks, merged. Let's keep an eye on it, though. There's a cron script that periodically recalculates the sort order for the implementations table, and it uses the URL in the name. You've stuck two URLs in there, so that may or may not throw the script off. We'll know by tomorrow.

**Comment by archiecobbs** [comment]
Ha, that's funny :) Thanks for the quick turnaround.

**Comment by ongardie** [comment]
Yeah, your sorting got thrown off. I removed the extra javadocs link in 23ab84d0; people should be able to find it from the README anyhow. The project should move up in the rankings in a few hours...

**Comment by archiecobbs** [comment]
Thanks.

**Pull request merged**
